version: 1.2.{build}
skip_tags: true
image: Visual Studio 2019 Preview

build_script:

- pwsh: ./build.ps1
artifacts:
- path: '**\*.nupkg'
  name: Nuget

deploy:
- provider: NuGet
  api_key:
    secure: SIQsAQejy/WB9cYfyIVemeDfRwvlarV5HXCuoq2ilTTBvDRBmujfGwDgLoJAJINv
